# Rules
The rules of Conways's Game are:
- **Birth rule**: An empty, or *dead*, cell with precisely three *live* neighbors (full cells) becomes live.
- **Death rule**: A live cell with zero or one neighbors dies of isolation; a live cell with four or more neighbors dies of overcrowding.
- **Survival rule**: A live cell with two or three neighbors remains alive.

**Note**. Everything is based on this [reference](https://www.nytimes.com/2020/12/28/science/math-conway-game-of-life.html)

I'm going to consider the *state of a cell* as below:

| State | Means |
|:-----:|:-----|
| 1 | Live Cell |
| 0 | Dead Cell |

In [1]:
import numpy as np

In [2]:
def rules(state:int, neighbors:np.array) -> int:
    if state == 1:
        # death rule
        if neighbors > 3 or neighbors < 2:
            return 0
        # survival rule
        elif neighbors == 2 or neighbors == 3:
            return 1
    # birth rule
    else:
        if neighbors == 3:
            return 1
        else:
            return 0

# Get status

In [3]:
def get_status(neighborhood:np.array) -> tuple:
    """ return the state and number of neighbor cells of a neighborhood """
    state = neighborhood[1,1]
    neighbors = neighborhood.sum() - state
    return state, neighbors

In [4]:
neighborhood = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [1, 1, 1]
])
get_status(neighborhood)

(1, 6)

# Update grid

In [8]:
grid = np.array([
    [1, 1, 1, 1, 1, 1],
    [0, 1, 1, 0, 1, 0],
    [1, 0, 0, 1, 0, 1],
    [0, 1, 0, 0, 1, 1],
    [1, 1, 0, 0, 1, 0],
    [1, 1, 0, 0, 1, 0]
])

def update_grid(grid:np.array) -> np.array:
    new_grid = grid.copy()
    for i in range(1, grid.shape[1] - 1):
        for j in range(1, grid.shape[0] - 1):
            neighborhood = grid[i-1:i+2, j-1:j+2]
            state, neighbors = get_status(neighborhood)
            new_grid[i, j] = rules(state, neighbors)
    return new_grid

In [9]:
update_grid(grid)

array([[1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 1],
       [0, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 0],
       [1, 1, 0, 0, 1, 0]])

In [10]:
oscilant = np.array([
    [0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0]
])

In [12]:
grid = oscilant.copy()
for _ in range(5):
    print(grid)
    grid = update_grid(grid)

[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]


In [13]:
oscilant2 = np.array([
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0],
    [0, 1, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0]
])

In [14]:
grid = oscilant2.copy()
for _ in range(5):
    print(grid)
    grid = update_grid(grid)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 1 0]
 [0 1 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 1 0]
 [0 1 0 0 1 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 1 0]
 [0 1 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 1 0 0 1 0]
 [0 1 0 0 1 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 1 0]
 [0 1 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [15]:
oscilant3 = np.array([
    [0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0],
    [0, 1, 1, 0, 0, 0],
    [0, 0, 0, 1, 1, 0],
    [0, 0, 0, 1, 1, 0],
    [0, 0, 0, 0, 0, 0]
])

In [16]:
grid = oscilant3.copy()
for _ in range(5):
    print(grid)
    grid = update_grid(grid)

[[0 0 0 0 0 0]
 [0 1 1 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 1 1 0]
 [0 0 0 1 1 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 1 1 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 1 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 1 1 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 1 1 0]
 [0 0 0 1 1 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 1 1 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 1 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 1 1 0 0 0]
 [0 1 1 0 0 0]
 [0 0 0 1 1 0]
 [0 0 0 1 1 0]
 [0 0 0 0 0 0]]
